### ISSUE TITLE
Error when deleting a variable from connected set <-> get variable blocks

### ISSUE THREAD

**Issue by gonfunko** [RaspberryPiFoundation/blockly#8455]
### Check for duplicates

- [X] I have searched for similar issues before opening a new one.

### Description

With a (fairly nonsensical) construction of blocks, deleting a variable from the dropdown menu causes an uncaught exception.

### Reproduction steps

1. Create a variable
2. Drag out and connect the "set \<x\> to" and "\<x\>" blocks
3. From the dropdown in the "set \<x\> to" block, choose the "Delete the 'x' variable" menu item
4. Observe the stack trace in the console

### Stack trace

```shell
Uncaught Error: The block associated with the block move event could not be found
    at BlockMove$$module$build$src$core$events$events_block_move.currentLocation_ (events_block_move.ts:202:17)
    at new BlockMove$$module$build$src$core$events$events_block_move (events_block_move.ts:93:27)
    at RenderedConnection$$module$build$src$core$rendered_connection.disconnectInternal (connection.ts:284:15)
    at RenderedConnection$$module$build$src$core$rendered_connection.disconnectInternal (rendered_connection.ts:453:11)
    at RenderedConnection$$module$build$src$core$rendered_connection.disconnect (connection.ts:259:10)
    at BlockSvg$$module$build$src$core$block_svg.unplugFromRow_ (block.ts:417:29)
    at BlockSvg$$module$build$src$core$block_svg.unplug (block.ts:398:12)
    at BlockSvg$$module$build$src$core$block_svg.dispose (block.ts:332:10)
    at BlockSvg$$module$build$src$core$block_svg.dispose (block_svg.ts:753:11)
    at VariableMap$$module$build$src$core$variable_map.deleteVariableInternal (variable_map.ts:307:17)Understand this error
```

### Screenshots

<img width="291" alt="Screenshot 2024-08-02 at 1 58 32 PM" src="https://github.com/user-attachments/assets/fc973846-cce1-4fdd-b94d-72f951814645">

**Comment by surajguduru** [comment]
Hey @gonfunko I would like to work on this issue. Can you assign it to me ?

**Comment by Naresh-kumar-Thodupunoori** [comment]
Hey @gonfunko May I work on this!!!

**Comment by aolney** [comment]
I had this or a very similar problem, and checking if the block still exists while disposing of multiple blocks seemed to solve:
```
 clearBlocks(): void {
    const workspace: Blockly.Workspace = Blockly.getMainWorkspace();
    const blocks = workspace.getAllBlocks(false);
    for (let i = 0; i < blocks.length; i++) {
      const block = blocks[i];
      //looks like disposing chains to child blocks, so check block exists b/f disposing
      if(workspace.getBlockById(block.id)) {  
        block.dispose(false);
      }
    }
```
